project:
  type: manuscript
  resources:
    - bibliography.bib
    - notebooks/*.qmd
  render:
    - index.qmd
    - notebooks/01_parcel_ETL.qmd
    - notebooks/02_corelogic.qmd
    - notebooks/03_cl_nc1map_id_match.qmd
    - notebooks/04_spatial_join.qmd
    - notebooks/05_spatial_match_app_mit.qmd
    - notebooks/05_alt_direct_match.qmd

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

execute:
  freeze: false

bibliography: bibliography.bib


