project:
  type: manuscript
  render:
    - "*.qmd"
    - "!science-advances/**"
  resources:
    - bibliography.bib
    - notebooks/*.qmd

manuscript:
  article: index.qmd

format:
  html:
    comments:
      hypothesis: true
  docx: default
  jats: default

execute:
  freeze: auto
website:
  repo-url: https://github.com/russblessing/Obstacles
  repo-actions: []

bibliography: bibliography.bib