{
  "hash": "95e060c0fd179a8be951ff6a3e0fe04f",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Step 5: Mitigations to Parcels\"\nauthor: \"Russell Blessing\"\nformat:\n  html:\n    toc: true\n    toc-depth: 3\n    code-fold: true\n    code-summary: \"Show / hide code\"\nexecute:\n  echo: true\n  warning: false\n  message: false\n---\n\n## Overview\n\nThis notebook spatially matches mitigation and application records to parcels\nusing a tiered priority scheme. Parcels are scored and ranked as high, medium,\nor low priority for matching based on land use code and address quality.\nFor each priority tier, mitigation/application geometries are first matched via\ndirect intersection with parcel polygons, then by nearest-neighbor distance\n(≤ 50 m) for those that do not intersect. Unmatched records after all three\ntiers fall back to a global nearest-neighbor match across all parcels.\n\n**Input files (Russell's):**\n\n- `nc1_cl_merge.csv` — parcel–CoreLogic merged table (Step 4 output)\n- `parcels_study_area.gpkg` — OneMap parcel geometries with `geometry_id`\n- `mit_newgeo.gpkg` — mitigations (re-geocoded)\n- `mit_elevation_qaqc_filled.csv` — elevation QAQC scores for mitigations\n- `applications_final.gpkg` — FEMA applications\n- `NC_huc6_data_union_sf.shp` — flood study area boundary\n\n**External files (written to `out_dir`):**\n\n- `parcels_matcheable.gpkg` — filtered parcels before priority scoring\n- `parcels_pri.gpkg` — parcels with priority scores\n- `mit_highpri.csv`, `mit_medpri.csv`, `mit_lowpri.csv`, `mit_dist.csv`\n- `app_highpri.csv`, `app_medpri.csv`, `app_lowpri.csv`, `app_dist.csv`\n- `app_sa_full_noqa.gpkg`, `mit_sa_full_noqa.gpkg`\n- `apps_pcls.gpkg`, `mits_pcls.gpkg`\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nlibrary(sf)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nLinking to GEOS 3.12.0, GDAL 3.11.0, PROJ 9.2.1; sf_use_s2() is TRUE\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(dplyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'dplyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:stats':\n\n    filter, lag\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following objects are masked from 'package:base':\n\n    intersect, setdiff, setequal, union\n```\n\n\n:::\n\n```{.r .cell-code .hidden}\nlibrary(readr)\nlibrary(stringr)\nlibrary(stringdist)\nlibrary(purrr)\nlibrary(tidyr)\n```\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\n\nAttaching package: 'tidyr'\n```\n\n\n:::\n\n::: {.cell-output .cell-output-stderr .hidden}\n\n```\nThe following object is masked from 'package:stringdist':\n\n    extract\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nout_dir  <- \"/proj/mhinolab/users/rbless/data/Obstacles_Output\"\n\n# External data paths\nflood_boundary_path <- \"/proj/mhinolab/projects/obstacles/NC_huc6_data_union_sf/NC_huc6_data_union_sf.shp\"\nmit_path            <- \"/proj/mhinolab/projects/obstacles2/CRC_May_2025/Raw Data Inputs/raw_app_ncb/mit_newgeo.gpkg\"\nmit_elev_path       <- \"/proj/mhinolab/projects/obstacles2/CRC_May_2025/Raw Data Inputs/raw_app_ncb/mit_elevation_qaqc_filled.csv\"\napp_path            <- \"/proj/mhinolab/projects/obstacles2/CRC_May_2025/Raw Data Inputs/raw_app_ncb/applications_final.gpkg\"\ngeoms_path          <- file.path(out_dir, \"parcels_study_area.gpkg\")\n```\n:::\n\n\n---\n\n## 1  Load & prepare parcels\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| eval: true\n\nparcels_raw <- read_csv(\n  file.path(out_dir, \"nc1_cl_merge.csv\"),\n  col_types = cols(.default = col_character())\n) |>\n  mutate(parcel_index = as.integer(parcel_index))\n\nnc1_geoms <- st_read(geoms_path, quiet = TRUE) |>\n  mutate(\n    parcel_index = as.integer(parcel_index),\n    geometry_id  = as.integer(factor(as.character(geom)))\n  ) |>\n  select(parcel_index, geometry_id)\n\nparcels <- parcels_raw |>\n  select(-any_of(c(\"geometry_id1\", \"index_right\", \"geometry_id\", \"geometry\"))) |>\n  left_join(st_drop_geometry(nc1_geoms), by = \"parcel_index\") |>\n  left_join(nc1_geoms |> select(parcel_index, geometry = geom), by = \"parcel_index\") |>\n  st_as_sf(crs = st_crs(nc1_geoms))\n```\n:::\n\n\n---\n\n## 2  Filter invalid parcels\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| eval: true\n\n# Remove water parcels (flagged via parcel number keywords)\nwater_keywords <- \"bay|creek|sound|water|ocean|river|canal|pond|inlet\"\n\nparcels <- parcels |>\n  filter(!str_detect(parno, regex(water_keywords, ignore_case = TRUE)))\n\n# Flag and remove invalid parcels\nparcels <- parcels |>\n  mutate(\n    invalidparcels = case_when(\n      # No identifying info at all\n      is.na(`LAND.USE.CODE`) & parno == \"\" & is.na(siteadd) & mailadd == \"\" ~ 1L,\n      # Carteret: no land use code, blank parno → likely right-of-way\n      is.na(`LAND.USE.CODE`) & parno == \"\" & cntyfips == \"031\" ~ 1L,\n      # Brunswick: no parno or altparno → right-of-way\n      is.na(`LAND.USE.CODE`) & parno == \"\" & altparno == \"\" & cntyfips == \"019\" ~ 1L,\n      # Explicit ROW tags (excluding \"ROWAN COUNTY\")\n      (str_detect(parno,    regex(\"row\", ignore_case = TRUE)) |\n       str_detect(altparno, regex(\"row\", ignore_case = TRUE))) &\n        parno != \"ROWAN COUNTY\" ~ 1L,\n      TRUE ~ 0L\n    )\n  ) |>\n  filter(invalidparcels == 0L)\n\n# Save pre-priority filtered parcels for diagnostic mapping\nst_write(parcels |> select(-invalidparcels),\n         file.path(out_dir, \"parcels_matcheable.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\n\nparcels <- parcels |> select(-invalidparcels)\n```\n:::\n\n\n---\n\n## 3  Parcel priority scoring\n\nLand use codes that define each priority bucket:\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nluc_vacant      <- c(\"465\",\"460\",\"455\",\"454\",\"453\",\"452\",\"450\",\"400\")\nluc_gov         <- c(\"604\",\"603\",\"601\",\"600\")     # +600 (E-Exempt) — parallels 601/603/604\nluc_residential <- c(\"165\",\"163\",\"160\",\"151\",\"138\",\"137\",\"136\",\"135\",\"134\",\"133\",\n                      \"132\",\"131\",\"117\",\"116\",\"115\",\"113\",\"112\",\"111\",\"109\",\"106\",\n                      \"103\",\"102\",\"100\")\nluc_fr_1_4      <- c(\"165\",\"163\",\"160\",\"151\",\"138\",\"137\",\"136\",\"135\",\n                      \"134\",\"133\",                # +133, 134 (triplex, quadruplex — definitional fix)\n                      \"132\",\"115\",\n                      \"113\",\"112\",\"111\",          # +111–113 (mobile/manufactured/modular — FEMA priority)\n                      \"102\",\"100\")\nluc_buyout      <- c(\"602\")                       # Hindsight — completed historical buyouts (LUC 602)\nluc_top         <- c(luc_vacant, luc_gov, luc_residential, luc_buyout)\nluc_bottom      <- c(\"283\",                       # +283 (commercial supermarket)\n                      \"605\",\"606\",\"607\",\"609\",\"610\",\"614\",\"615\",\"618\",\"620\",\"630\",\n                      \"800\",\"818\",\"839\",\"850\",\"860\",\"872\",\"875\",\"877\",\"880\",\"883\",\n                      \"885\",\"886\",\"114\")\n```\n:::\n\n\n**Scoring change from original Python script**\n\nThe original script collapsed vacant, government-owned, and all residential\nparcels into a single `qual_luc = 3` bucket, meaning a 1–4 family home and\na municipal lot were treated identically. It also weighted site address and\nmailing address equally (1 pt each), and the composite `qual_sum` only\nranged 0–5, making the high/med/low thresholds somewhat arbitrary.\n\nThe revised scheme, with hindsight-specific elevation for completed buyouts:\n\n| LUC group | `luc_tier` | `match_priority` | Rationale |\n|---|---|---|---|\n| Completed buyouts (`luc_buyout`, LUC 602) | 3 | high (always) | Hindsight: confirmed historical buyout — parcel converted to exempt status *because of* the program we're studying |\n| 1–4 family residential (`luc_fr_1_4`) | 4 | high if site address present | Primary buyout/mitigation candidate; includes mobile/manufactured/modular housing per FEMA HMA priorities |\n| Vacant land (`luc_vacant`) | 3 | med | High candidate, no structure risk |\n| Gov-owned (`luc_gov`) | 3 | med | Eligible but less common |\n| Other residential (`luc_residential \\ luc_fr_1_4`) | 2 | med if qual_sum ≥ 5, else low | Multi-family / condo / apartment — rarely targeted |\n| Unknown LUC | 1 | low | Insufficient info |\n| Commercial/industrial (`luc_bottom`) | 0 | low | Unlikely candidates |\n\nSite address is weighted **2 pts** (more useful for geocoding/matching than\nmailing address), mailing address **1 pt**, giving a `qual_sum` range of\n0–7 and more granular priority tiers.\n\n**`luc_fr_1_4` membership reflects FEMA HMA program priorities** rather\nthan CoreLogic's literal numeric subgroupings:\n\n- LUC 111 (\"Mobile home\"), 112 (\"Manufactured home\"), 113 (\"Modular home\")\n  are included to reflect FEMA's documented emphasis on mobile/manufactured/\n  modular housing in flood-prone areas.\n- LUC 133 (\"Triplex\") and 134 (\"Quadruplex\") added for definitional\n  consistency with the \"1–4 family\" label — both are 2–4 unit residential\n  and were missing from the original list.\n\n**Code list corrections from the original Python:**\n\n- The `gov` list had a missing comma bug (`['604' '603', '601']` → the\n  string `'604603'`), so no parcel ever matched it. Fixed here.\n- LUC 600 (\"E-Exempt\") added to `luc_gov` — parallels the existing\n  601/603/604 exempt-government codes.\n- LUC 283 (CoreLogic commercial) added to `luc_bottom`.\n- LUC 602 (\"Exempt Governmental (Flood Buyout)\") added as a separate\n  `luc_buyout` flag. Treated as tier 3 in `luc_tier` (current state =\n  exempt government) and elevated to `match_priority = \"high\"` for\n  the hindsight analysis — a mit/app record landing on a 602 parcel\n  is a confirmed historical buyout, the strongest possible match signal.\n  \n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| eval: true\n\nparcels <- parcels |>\n  mutate(\n    `LAND.USE.CODE` = as.character(`LAND.USE.CODE`),\n\n    # Land use flags (kept for downstream use)\n    vacant              = if_else(`LAND.USE.CODE` %in% luc_vacant,      1L, 0L),\n    gov_lu              = if_else(`LAND.USE.CODE` %in% luc_gov,         1L, 0L),\n    res_lu              = if_else(`LAND.USE.CODE` %in% luc_residential, 1L, 0L),\n    fr_1_4              = if_else(`LAND.USE.CODE` %in% luc_fr_1_4,      1L, 0L),\n    is_completed_buyout = `LAND.USE.CODE` %in% luc_buyout,\n\n    # Address quality: site address weighted 2x, mail address 1x\n    qual_siteadd = if_else(!is.na(siteadd) & siteadd != \"\", 2L, 0L),\n    qual_mailadd = if_else(!is.na(mailadd) & mailadd != \"\", 1L, 0L),\n\n    # Tiered LUC score (0–4) — reflects current CoreLogic classification\n    luc_tier = case_when(\n      `LAND.USE.CODE` %in% luc_fr_1_4                                        ~ 4L,\n      `LAND.USE.CODE` %in% luc_vacant                                         ~ 3L,\n      `LAND.USE.CODE` %in% luc_gov                                            ~ 3L,\n      `LAND.USE.CODE` %in% luc_buyout                                         ~ 3L,\n      `LAND.USE.CODE` %in% luc_residential & !`LAND.USE.CODE` %in% luc_fr_1_4 ~ 2L,\n      `LAND.USE.CODE` %in% luc_bottom                                         ~ 0L,\n      TRUE                                                                     ~ 1L\n    ),\n\n    # Composite score (0–7) and priority tier\n    qual_sum = luc_tier + qual_siteadd + qual_mailadd,\n    match_priority = case_when(\n      is_completed_buyout                ~ \"high\",   # Hindsight: confirmed historical buyout\n      luc_tier == 4 & qual_siteadd == 2  ~ \"high\",   # 1–4 family + site address\n      luc_tier >= 3 | qual_sum >= 5      ~ \"med\",\n      TRUE                               ~ \"low\"\n    )\n  )\n\n# Save prioritised parcel layer\nst_write(parcels, file.path(out_dir, \"parcels_pri.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#| eval: true\n\n# Split into priority tiers\nhighpri <- parcels |> filter(match_priority == \"high\")\nmedpri  <- parcels |> filter(match_priority == \"med\")\nlowpri  <- parcels |> filter(match_priority == \"low\")\n```\n:::\n\n\n---\n\n## 4  Load & prepare mitigations and applications\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nflood_boundary <- st_read(flood_boundary_path, quiet = TRUE) |>\n  st_transform(crs = 32119)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_gdf <- st_read(mit_path, quiet = TRUE) |>\n  st_transform(crs = st_crs(flood_boundary))\n\n# Merge elevation QAQC scores\nmit_elev <- read_csv(mit_elev_path, col_types = cols(.default = col_character())) |>\n  rename_with(str_trim)\n\nmit_gdf <- mit_gdf |>\n  left_join(mit_elev |> \n  select(record_ID, elevation_score), by = \"record_ID\")\n\n# Clip to study area\nmit_gdf <- mit_gdf |>\n  mutate(Inside_SA = as.integer(lengths(st_within(st_geometry(mit_gdf), flood_boundary)) > 0))\n\nmit_sa <- mit_gdf |> filter(Inside_SA == 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\napp <- st_read(app_path, quiet = TRUE) |>\n  st_transform(crs = st_crs(flood_boundary))\n\napp <- app |>\n  mutate(\n    app_id    = row_number(),\n    Inside_SA = as.integer(lengths(st_within(st_geometry(app), flood_boundary)) > 0)\n  )\n\napp_sa <- app |> filter(Inside_SA == 1)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_geom_col <- attr(mit_sa, \"sf_column\")\napp_geom_col <- attr(app_sa, \"sf_column\")\n\nmit_sa <- mit_sa |>\n  mutate(g_indicator = as.integer(factor(as.character(st_geometry(mit_sa)))))\n\napp_sa <- app_sa |>\n  mutate(\n    g_indicator = as.integer(factor(as.character(st_geometry(app_sa)))),\n    app_id      = row_number()\n  )\n\nunique_mit <- mit_sa |> distinct(g_indicator, .keep_all = TRUE) |>\n  select(g_indicator, all_of(mit_geom_col)) |>\n  st_transform(crs = st_crs(flood_boundary))\n\nunique_app <- app_sa |> distinct(g_indicator, .keep_all = TRUE) |>\n  select(g_indicator, all_of(app_geom_col)) |>\n  st_transform(crs = st_crs(flood_boundary))\n```\n:::\n\n\n---\n\n## 5  Build unique-geometry sets\n\nMatching is done on unique geometries then merged back, avoiding redundant\nspatial operations where multiple records share a coordinate.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nread_priority <- function(priority, path) {\n  st_read(\n    path,\n    query = paste0(\"SELECT parcel_index, match_priority, geometry_id, geom FROM \\\"parcels_pri\\\" WHERE match_priority = '\", priority, \"'\"),\n    quiet = TRUE\n  ) |>\n    st_transform(crs = 32119)\n}\n\nparcels_path <- file.path(out_dir, \"parcels_pri.gpkg\")\n\nhighpri <- read_priority(\"high\", parcels_path)\nmedpri  <- read_priority(\"med\",  parcels_path)\nlowpri  <- read_priority(\"low\",  parcels_path)\ngc()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n             used   (Mb) gc trigger    (Mb)   max used    (Mb)\nNcells  100258977 5354.5  166164114  8874.2  166164114  8874.2\nVcells 1184118411 9034.2 2216865219 16913.4 1986525679 15156.0\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Reproject parcel priority sets to EPSG:32119\nto_unique_geoms <- function(df) {\n  geom_col <- attr(df, \"sf_column\")\n  df |>\n    st_transform(crs = 32119) |>\n    distinct(geometry_id, .keep_all = TRUE) |>\n    select(geometry_id, all_of(geom_col)) |>\n    rename(geometry = all_of(geom_col))\n}\n\nug_high <- to_unique_geoms(highpri)\nug_med  <- to_unique_geoms(medpri)\nug_low  <- to_unique_geoms(lowpri)\n```\n:::\n\n\n\n---\n\n## 6  Tiered spatial matching helper\n\nA single function runs the intersect → distance (≤ 50 m) workflow for one\npriority tier, for both mitigations and applications.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n#' Match unique geometries to a parcel tier via intersect + nearest-neighbour\n#'\n#' @param candidates sf with columns g_indicator + geometry (mit or app unique geoms)\n#' @param parcel_tier sf with columns geometry_id + geometry (unique parcel geoms)\n#' @param max_dist   maximum allowable distance in metres for distance matches\n#'\n#' @return tibble with columns g_indicator, geometry_id, and optionally distance\nmatch_to_tier <- function(candidates, parcel_tier, max_dist = 50) {\n\n  # --- intersect pass ---\n  intersect_raw <- st_join(candidates, parcel_tier, join = st_intersects, left = TRUE)\n\n  intersect_matched <- intersect_raw |>\n    filter(!is.na(geometry_id)) |>\n    st_drop_geometry() |>\n    mutate(intersect = 1L) |>\n    distinct(g_indicator, .keep_all = TRUE)\n\n  unmatched <- intersect_raw |>\n    filter(is.na(geometry_id)) |>\n    select(g_indicator)\n\n  # --- distance pass on the remainder ---\n  if (nrow(unmatched) == 0 || nrow(parcel_tier) == 0) {\n    dist_matched <- tibble(g_indicator = integer(), geometry_id = integer(),\n                           distance = numeric())\n  } else {\n    dist_joined <- st_join(unmatched, parcel_tier, join = st_nearest_feature)\n\n    parcel_geoms <- parcel_tier$geometry[match(dist_joined$geometry_id, parcel_tier$geometry_id)]\n\n    dist_matched <- dist_joined |>\n      mutate(distance = as.numeric(\n        st_distance(st_geometry(dist_joined), parcel_geoms, by_element = TRUE)\n      )) |>\n      st_drop_geometry() |>\n      distinct(g_indicator, .keep_all = TRUE) |>\n      filter(distance <= max_dist)\n  }\n\n  bind_rows(\n    intersect_matched |> select(g_indicator, geometry_id),\n    dist_matched      |> select(g_indicator, geometry_id, any_of(\"distance\"))\n  )\n}\n```\n:::\n\n\n---\n\n## 7  Run tiered matching\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_highpri <- match_to_tier(unique_mit, ug_high)\napp_highpri <- match_to_tier(unique_app, ug_high)\n\n# Remove matched records before next tier\nmits_rem <- unique_mit |> filter(!g_indicator %in% mit_highpri$g_indicator)\napps_rem <- unique_app |> filter(!g_indicator %in% app_highpri$g_indicator)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_medpri <- match_to_tier(mits_rem, ug_med)\napp_medpri <- match_to_tier(apps_rem, ug_med)\n\nmits_rem <- mits_rem |> filter(!g_indicator %in% mit_medpri$g_indicator)\napps_rem <- apps_rem |> filter(!g_indicator %in% app_medpri$g_indicator)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_lowpri <- match_to_tier(mits_rem, ug_low)\napp_lowpri <- match_to_tier(apps_rem, ug_low)\n\nmits_rem <- mits_rem |> filter(!g_indicator %in% mit_lowpri$g_indicator)\napps_rem <- apps_rem |> filter(!g_indicator %in% app_lowpri$g_indicator)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Fallback: global nearest-neighbour across all parcel tiers (no distance cap)\nug_all <- bind_rows(ug_high, ug_med, ug_low)\n\nnn_fallback <- function(remaining, all_geoms) {\n  if (nrow(remaining) == 0) {\n    return(tibble(g_indicator = integer(), geometry_id = integer(),\n                  distance = numeric()))\n  }\n  joined <- st_join(remaining, all_geoms, join = st_nearest_feature)\n  joined |>\n    mutate(distance = as.numeric(\n      st_distance(\n        st_geometry(joined),\n        all_geoms$geometry[match(geometry_id, all_geoms$geometry_id)],\n        by_element = TRUE\n      )\n    )) |>\n    st_drop_geometry() |>\n    distinct(g_indicator, .keep_all = TRUE) |>\n    select(g_indicator, geometry_id, distance)\n}\n\nmit_dist <- nn_fallback(mits_rem, ug_all)\napp_dist <- nn_fallback(apps_rem, ug_all)\n```\n:::\n\n\n---\n\n## 8  Save per-tier CSVs\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nwrite_csv(mit_highpri, file.path(out_dir, \"mit_highpri.csv\"))\nwrite_csv(app_highpri, file.path(out_dir, \"app_highpri.csv\"))\nwrite_csv(mit_medpri,  file.path(out_dir, \"mit_medpri.csv\"))\nwrite_csv(app_medpri,  file.path(out_dir, \"app_medpri.csv\"))\nwrite_csv(mit_lowpri,  file.path(out_dir, \"mit_lowpri.csv\"))\nwrite_csv(app_lowpri,  file.path(out_dir, \"app_lowpri.csv\"))\nwrite_csv(mit_dist,    file.path(out_dir, \"mit_dist.csv\"))\nwrite_csv(app_dist,    file.path(out_dir, \"app_dist.csv\"))\n```\n:::\n\n\n---\n\n## 9  Merge geometry tags back to full mit / app datasets\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nmit_geom_full <- bind_rows(mit_highpri, mit_medpri, mit_lowpri, mit_dist)\napp_geom_full <- bind_rows(app_highpri, app_medpri, app_lowpri, app_dist)\n\nmit_sa_full <- mit_sa |>\n  mutate(unique_id = row_number()) |>\n  left_join(mit_geom_full, by = \"g_indicator\")\n\napp_sa_full <- app_sa |>\n  mutate(unique_id = row_number()) |>\n  left_join(app_geom_full, by = \"g_indicator\")\n\n# Save geometry-tagged full datasets before QA\nst_write(app_sa_full, file.path(out_dir, \"app_sa_full_noqa.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\nst_write(mit_sa_full, file.path(out_dir, \"mit_sa_full_noqa.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\n```\n:::\n\n\n---\n\n## 10  Join back to parcels\n\nThe spatial matching in steps 1–9 assigns each mit/app record a `geometry_id`\n— the identifier of the parcel polygon it fell inside or nearest to. The goal\nhere is to recover the full parcel attribute table (owner, land use, address,\nimprovement value, etc.) and the parcel geometry for every matched record.\n\nThe complication is that `geometry_id` is not a unique key into `parcels_nogeom`.\nTwo situations produce a many-to-many relationship:\n\n1. **Condo / multi-unit complexes.** Each individual unit (e.g., the 95 units at\n   9620–9630 Vinca Circle) is a separate legal parcel with its own APN, but all\n   units are registered against the same polygon, so they all share one\n   `geometry_id`. The mit/app address (e.g., *\"9624 VINCA CIR APT C\"*) identifies\n   one specific unit, not the whole complex.\n\n2. **Recorder duplicates.** A small number of geometry_ids have 2–6 parcel rows\n   that differ only in `APN.SEQUENCE.NUMBER`. The row with `APN.SEQUENCE.NUMBER = 1`\n   is the primary (canonical) recorder entry; the others are supplemental filings.\n\nTo resolve both cases without inflating the output row count, a two-stage\nselection is applied within each duplicate `geometry_id` group:\n\n- **Stage 1 — address similarity.** Jaro-Winkler string similarity is computed\n  between the mit/app address field and each candidate parcel's `siteadd`. The\n  candidate(s) with the highest similarity score are retained. This is the\n  decisive criterion for condo complexes where `APN.SEQUENCE.NUMBER` is 1 for\n  every unit.\n- **Stage 2 — tiebreaking.** Among remaining ties (equal similarity scores),\n  records are ranked by `APN.SEQUENCE.NUMBER` ascending (primary recorder entry\n  first), then `luc_tier` descending (most specific land use), then `improvval`\n  descending (parcel with a structure). A single winner is taken.\n\nNon-duplicate `geometry_id`s bypass this logic entirely and are joined directly.\nThe two paths are recombined before the geometry attachment and file write.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nn_mits_rem <- nrow(mits_rem)\nn_apps_rem <- nrow(apps_rem)\n\nrm(ug_high, ug_med, ug_low, ug_all,\n   highpri, medpri, lowpri,\n   mit_highpri, app_highpri, mit_medpri, app_medpri,\n   mit_lowpri, app_lowpri, mit_dist, app_dist,\n   unique_mit, unique_app, mits_rem, apps_rem)\ngc()\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n            used   (Mb) gc trigger    (Mb)   max used    (Mb)\nNcells  70248897 3751.7  192954100 10304.9  241192624 12881.1\nVcells 936624430 7145.9 2216865219 16913.4 2216865195 16913.4\n```\n\n\n:::\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nparcels_nogeom <- st_read(parcels_path, quiet = TRUE) |>\n  st_drop_geometry() |>\n  select(-any_of(c(\"vacant\",\"gov_lu\",\"res_lu\",\"fr_1_4\",\n                   \"qual_siteadd\",\"qual_mailadd\",\"qual_luc\",\n                   \"qual_sum\",\"match_priority\")))\n                   \n# Reconstruct nc1_geoms for final geometry join (load-parcels is eval:false)\nnc1_geoms <- st_read(geoms_path, quiet = TRUE,\n                     query = 'SELECT parcel_index, geom FROM parcels_study_area') |>\n  mutate(parcel_index = as.integer(parcel_index))\n\n# Drop geometry from app/mit before joining\napps_nogeom <- app_sa_full |> st_drop_geometry()\nmits_nogeom <- mit_sa_full |> st_drop_geometry()\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# --- Identify geometry_ids with multiple parcel rows ---\ndup_geom_ids <- parcels_nogeom |>\n  count(geometry_id) |>\n  filter(n > 1) |>\n  pull(geometry_id)\n\n# --- Helper: pick the best parcel for one (record, geometry_id) pair ----------\n# Priority:\n#   1. Highest address similarity (Jaro-Winkler) between record address and siteadd\n#   2. Lowest APN.SEQUENCE.NUMBER (primary recorder record)\n#   3. Highest luc_tier (most specific land use)\n#   4. Highest improvval (parcel has a structure)\npick_best_parcel <- function(records_nogeom, addr_col) {\n  dup_pool <- parcels_nogeom |>\n    filter(geometry_id %in% dup_geom_ids)\n\n  records_nogeom |>\n    filter(geometry_id %in% dup_geom_ids) |>\n    select(unique_id, geometry_id, raw_addr = all_of(addr_col)) |>\n    left_join(dup_pool, by = \"geometry_id\", relationship = \"many-to-many\") |>\n    mutate(\n      addr_sim = stringsim(\n        toupper(coalesce(raw_addr, \"\")),\n        toupper(coalesce(siteadd,  \"\")),\n        method = \"jw\"\n      )\n    ) |>\n    group_by(unique_id, geometry_id) |>\n    slice_max(addr_sim,             n = 1, with_ties = TRUE) |>\n    slice_min(APN.SEQUENCE.NUMBER,  n = 1, with_ties = TRUE) |>\n    slice_max(luc_tier,             n = 1, with_ties = TRUE) |>\n    slice_max(improvval,            n = 1, with_ties = FALSE) |>\n    ungroup() |>\n    select(unique_id, geometry_id, parcel_index)\n}\n\napp_winners <- pick_best_parcel(apps_nogeom |> mutate(unique_id = row_number()), \"address\")\nmit_winners <- pick_best_parcel(mits_nogeom |> mutate(unique_id = row_number()), \"raw_addr\")\n\n# --- Build deduplicated parcel tables scoped to each record type ---------------\n# For non-dup geometry_ids: keep all parcel rows (1-to-1, no change)\n# For dup geometry_ids:     keep only the winner row per (unique_id, geometry_id)\nparcels_nogeom_app_dedup <- parcels_nogeom |>\n  filter(!geometry_id %in% dup_geom_ids)   # non-dup rows\n\nparcels_nogeom_mit_dedup <- parcels_nogeom_app_dedup  # same base\n\n# Winner rows — join winner parcel_index back to full parcel attributes\napp_dup_rows <- app_winners |>\n  left_join(parcels_nogeom, by = c(\"geometry_id\", \"parcel_index\"))\n\nmit_dup_rows <- mit_winners |>\n  left_join(parcels_nogeom, by = c(\"geometry_id\", \"parcel_index\"))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\n# Join mit/app → parcel attributes via geometry_id, then attach parcel geometry.\n# Dup geometry_ids use the address-similarity winner; non-dup geometry_ids join\n# normally (no many-to-many inflation).\n\njoin_dedup <- function(records_nogeom, dup_rows, id_col, nc1_geoms) {\n  id_sym <- sym(id_col)\n\n  non_dup <- records_nogeom |>\n    mutate(.uid = row_number()) |>\n    filter(!geometry_id %in% dup_geom_ids) |>\n    left_join(parcels_nogeom_app_dedup, by = \"geometry_id\")\n\n  dup <- records_nogeom |>\n    mutate(.uid = row_number()) |>\n    filter(geometry_id %in% dup_geom_ids) |>\n    left_join(\n      dup_rows |> select(unique_id, geometry_id, parcel_index,\n                         any_of(names(parcels_nogeom))),\n      by = c(\".uid\" = \"unique_id\", \"geometry_id\")\n    )\n\n  bind_rows(non_dup, dup) |>\n    distinct() |>\n    left_join(nc1_geoms |> select(parcel_index, geometry = geom),\n              by = \"parcel_index\") |>\n    select(-.uid) |>\n    st_as_sf(crs = st_crs(nc1_geoms))\n}\n\napps_pcls <- join_dedup(\n  apps_nogeom |> mutate(unique_id = row_number()),\n  app_dup_rows, \"unique_id\", nc1_geoms\n)\n\nmits_pcls <- join_dedup(\n  mits_nogeom |> mutate(unique_id = row_number()),\n  mit_dup_rows, \"unique_id\", nc1_geoms\n)\n\nst_write(apps_pcls, file.path(out_dir, \"apps_pcls.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\nst_write(mits_pcls, file.path(out_dir, \"mits_pcls.gpkg\"),\n         delete_dsn = TRUE, quiet = TRUE)\n```\n:::\n\n\n---\n\n## Summary\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\npri_cols <- cols(g_indicator = col_integer(), geometry_id = col_integer(), distance = col_double())\n\nmit_highpri <- read_csv(file.path(out_dir, \"mit_highpri.csv\"), col_types = pri_cols)\napp_highpri <- read_csv(file.path(out_dir, \"app_highpri.csv\"), col_types = pri_cols)\nmit_medpri  <- read_csv(file.path(out_dir, \"mit_medpri.csv\"),  col_types = pri_cols)\napp_medpri  <- read_csv(file.path(out_dir, \"app_medpri.csv\"),  col_types = pri_cols)\nmit_lowpri  <- read_csv(file.path(out_dir, \"mit_lowpri.csv\"),  col_types = pri_cols)\napp_lowpri  <- read_csv(file.path(out_dir, \"app_lowpri.csv\"),  col_types = pri_cols)\nmit_dist    <- read_csv(file.path(out_dir, \"mit_dist.csv\"),    col_types = pri_cols)\napp_dist    <- read_csv(file.path(out_dir, \"app_dist.csv\"),    col_types = pri_cols)\n```\n:::\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\ntibble::tibble(\n  Type        = c(\"Mitigations\", \"Applications\"),\n  Total       = c(nrow(mit_sa),      nrow(app_sa)),\n  High        = c(nrow(mit_highpri), nrow(app_highpri)),\n  Med         = c(nrow(mit_medpri),  nrow(app_medpri)),\n  Low         = c(nrow(mit_lowpri),  nrow(app_lowpri)),\n  Fallback_NN = c(nrow(mit_dist),    nrow(app_dist)),\n  Unmatched   = c(n_mits_rem,    n_apps_rem)\n) |>\n  dplyr::mutate(\n    Matched = High + Med + Low + Fallback_NN\n  ) |>\n  dplyr::select(Type, Total, High, Med, Low, Fallback_NN, Matched, Unmatched) |>\n  knitr::kable(\n    format.args = list(big.mark = \",\"),\n    col.names   = c(\"Type\", \"Total\", \"High\", \"Med\", \"Low\", \"Fallback NN\",\n                    \"Total Matched\", \"Unmatched\")\n  )\n```\n\n::: {.cell-output-display}\n\n\n|Type         |  Total|  High|   Med| Low| Fallback NN| Total Matched| Unmatched|\n|:------------|------:|-----:|-----:|---:|-----------:|-------------:|---------:|\n|Mitigations  |  8,801| 6,173| 1,031| 146|           5|         7,355|         5|\n|Applications | 23,232| 8,674| 1,243| 364|          15|        10,296|        15|\n\n\n:::\n:::\n\n\n---\n\n## Comparison with previous analysis\n\nThe table below compares final matched parcel counts between this run and the\nprior team's Python-based pipeline. Differences stem from five sources:\n\n1. **Input record counts** — the source `.gpkg` files have been updated since\n   the prior run (mitigations: 8,801 vs. 8,803; applications: 23,232 vs. 23,256).\n\n2. **Priority scoring revision** — the original `gov` LUC list had a missing\n   comma bug (`['604' '603', '601']`), meaning no parcel ever matched that\n   category. The revised scheme also separates 1–4 family residential into its\n   own tier and weights site address 2× mailing address, producing a cleaner\n   high/med/low split.\n\n3. **Geometry deduplication method** — the prior script assigned `g_indicator`\n   via `groupby('geometry').ngroup()`, which groups on WKT string\n   representations. Two geometries that are visually identical but differ by\n   sub-micron floating-point precision will receive different group IDs,\n   potentially inflating unique geometry counts. This pipeline uses\n   `factor(as.character(st_geometry(.)))`, which is consistent with how R\n   represents geometries and avoids this edge case.\n\n4. **Low-priority parcel pool asymmetry** — the prior script correctly excluded\n   high-priority geometry IDs from the medium-priority pool, but failed to\n   exclude medium-priority IDs from the low-priority pool. This slightly\n   inflated the low-priority candidate set, allowing some geometries to be\n   matched twice across tiers. This pipeline uses sequential remainder sets\n   (`mits_rem` / `apps_rem`) so each geometry can only match in one tier.\n\n5. **Parcel duplicate preservation** — the Python pipeline's final\n   `merge(apps, parcels, on='geometry_id')` naturally re-inflates matched\n   records across all parcel rows that share a `geometry_id` (i.e. a common\n   physical footprint). \n\n6. **Duplicate-geometry deduplication** — this pipeline resolves the 39\n   `geometry_id`s with multiple candidate parcel rows by selecting a single\n   winner per record using address similarity (Jaro-Winkler on `siteadd`) with\n   `APN.SEQUENCE.NUMBER`, `luc_tier`, and `improvval` as tiebreakers. The prior\n   pipeline retained all matching rows, inflating parcel counts.\n\n\n::: {.cell}\n\n```{.r .cell-code .hidden}\nn_mit_pcls <- n_distinct(mits_pcls$parcel_index)\nn_app_pcls <- n_distinct(apps_pcls$parcel_index)\nn_both     <- length(intersect(mits_pcls$parcel_index, apps_pcls$parcel_index))\npct_both   <- round(n_both / n_app_pcls * 100, 1)\n\ntibble::tibble(\n  Metric      = c(\"Parcels with a mitigation\",\n                  \"Parcels with an application\",\n                  \"Parcels with both (mit \\u2229 app)\",\n                  \"Share of app parcels with a mit\"),\n  `Prior run` = c(\"6,087\", \"8,782\", \"4,292\", \"48.9%\"),\n  `This run`  = c(\n    format(n_mit_pcls, big.mark = \",\"),\n    format(n_app_pcls, big.mark = \",\"),\n    format(n_both,     big.mark = \",\"),\n    paste0(pct_both, \"%\")\n  )\n) |>\n  knitr::kable(align = c(\"l\", \"r\", \"r\"))\n```\n\n::: {.cell-output-display}\n\n\n|Metric                          | Prior run| This run|\n|:-------------------------------|---------:|--------:|\n|Parcels with a mitigation       |     6,087|    5,836|\n|Parcels with an application     |     8,782|    8,523|\n|Parcels with both (mit ∩ app)   |     4,292|    4,137|\n|Share of app parcels with a mit |     48.9%|    48.5%|\n\n\n:::\n:::\n\n\nDespite the count differences, the share of application parcels that also\nreceived a mitigation is nearly identical across both runs (48.9%\nvs. 48.5%), suggesting the matching logic is consistent —\nthe absolute differences are driven by input data updates and the scoring,\ndeduplication, and parcel duplicate-preservation fixes above.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}